### PR TITLE
Patch extensions

### PR DESCRIPTION
**Pull request by maraino**
This change adds support for patching operations under schema extensions.

 Currently a patch like this will fail with a 400 error, but it's valid way to add the attribute value of the extension urn:scim:my:custom:schema.
 ```json
 {
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "urn:scim:my:custom:schema:value",
            "value": 1234
        }
    ]
}
```

### CODE REVIEW

**Comment by maraino** [comment]
@di-wu due that all the types are passed by value, so copied every time, I see a couple of options:
1. A simple one that will force the user to set an `Extension: true` in the schema.
2. Add a new parameter `extension bool` to `Schema.ValidatePatchOperationValue`, or to be backward compatible create a new method, i.e `Schema.ValidatePatchOperation(operation string, operationValue map[string]interface{}, extension bool)` that is called from `ResourceType.validateOperationValue` on each extension.

I like the second option better. What do you think?

**Comment by di-wu** [comment]
I am sorry this took so long, I hope to reply faster next time!

1. We should try to prevent 'extending' SCIM by defining a field `extension: bool` if possible.
2. Is it not possible to check for a prefix before validating the patch value by checking the schema extensions of that resource type? We already did that in the validate function of resource types.

https://github.com/elimity-com/scim/blob/a6c0de0efada284d0abdd546377d08134f459ba8/resource_type.go#L65-L80

**Comment by maraino** [comment]
> 2. Is it not possible to check for a prefix before validating the patch value by checking the schema extensions of that resource type? We already did that in the validate function of resource types.

@di-wu I'm not sure If I understand your intention properly, but what I did in my last commit was to only check the extension with the right prefix, instead of looping through all the extensions as before.

So I'm implementing my second option, and instead of checking directly the schema.ID as before, I added a new method with an extra parameter (`isExtension`) and in `ValidatePatchOperationValue`, I just call this new method with `isExtension` set to false.
```go
func (s Schema) ValidatePatchOperation(operation string, operationValue map[string]interface{}, isExtension bool) errors.ValidationError {
   // previous logic of ValidatePatchOperationValue + fix
}

func (s Schema) ValidatePatchOperationValue(operation string, operationValue map[string]interface{}) errors.ValidationError {
	return s.ValidatePatchOperation(operation, operationValue, false)
}
```

**Comment by becoded** [comment]
@di-wu, it seems that this merge broke the TestJSONMarshalling test.

**Comment by di-wu** [comment]
Thank you for letting me know!

**Pull request merged**
